### ISSUE TITLE
Cone indices and list direction

### ISSUE THREAD

**Issue by jamievicary** [NickHu/homotopy-core#16]
A rewrite contains a list of cones. Suppose we have a list

    c1 : c2 : c3 : Nil

There is a coordinate system describing these cones, with respect which their "index" parameter is defined. Clearly the index parameter doesn't vary arbitrarily along the list; it is either non-increasing, or non-decreasing, depending on the convention that we have chosen.

The question is whether c3 should have the smallest value of the index parameter, or if c1 has the smallest parameter. I believe it would make a lot of sense for c3 to have the smallest parameter, as that way the base case of recursion is sitting at the coordinate origin.

Nick and I discussed this today and we weren't completely sure which was intended. Lukas, can you confirm what the convention is?

It's important for everyone to be clear on the convention so that mistake aren't made. Note that the right-to-left convention that I'm hoping for above is in some sense counterintuitive to the normal expectation that the origin for the coordinate system should be "on the left", since the item c3 is at the right of the list as represented above, not at the left.

**Comment by zrho** [comment]
The indices are ascending from left to right, so c1 has the smallest
parameter. I believe that this is also the convention used by the js
implementation.

Right to left would have the advantage that for rewrites, while iterating
over the cones, there wouldn't be a need to keep track of the offset
induced by the cones that come before. Left to right appears a lot better
every time you need to find out the target index while iterating, or any
other metric that that depends on the cones that have smaller index.

**Comment by jamievicary** [comment]
OK. It would be great to discuss this in more detail -- shall we jump
into a zoom if people are online?

The current implementation uses arrays, which can be accessed just as
easily forwards or backwards.

**Comment by jamievicary** [comment]
It turns out I'm not free now, but how about we talk later -- 2pm UK time would work for me.
