### ISSUE TITLE
Implement layout

### ISSUE THREAD

**Issue by NickHu** [NickHu/homotopy-core#2]
We can probably start with just 2D for now

**Comment by zrho** [comment]
2D layout has been implemented now, with a variation on the naive algorithm that generates a lot of distance and average constraints and solves them by eagerly propagating the constraints. To make this a bit faster, average constraints between two individual positions are interpreted by treating the positions as one variable. I haven't tested performance of this concrete implementation on large examples yet, but the performance was mostly fine for all but excessively large input diagrams in prior testing. We can see if layout performance becomes a problem in the future.

This optimization uses the special property of 2D layout that there always exists a solution in which all the constraints are satisfied. 
This does not hold in 3D, so a more sophisticated algorithm will have to be written for that. I'm closing this issue for now, so we can come back to 3D layout later after the basic functionality is done.
